name: icapps_translations
description: Dart tool to generate flutter translations code from the icapps translations tool
version: 10.0.1
homepage: https://github.com/icapps/flutter-icapps-translations

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.6
  locale_gen: ^11.0.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
